### ISSUE TITLE
more transparent

### ISSUE THREAD

**Issue by mrbrdo** [Kalroth/cgminer-3.7.2-kalroth#1]
Hey, nice job.

It would be nice to have a real fork of cgminer, to make it more transparent what the actual changes are. I already did this if you want: https://github.com/mrbrdo/cgminer/tree/kalroth

Also I belive this commit can be removed (which I have done in my master branch, which is same just without this commit): https://github.com/mrbrdo/cgminer/commit/e08ffb08902d7a927b26fe3d6e8c080a3e2dd141
This is the diff between cgminer's v3.7.2 official release and what you had in your "initial clone" commit. I think it is irrelevant and does not affect anything (except the readme which you can add back). Or could you also explain why you removed certain files and added certain (like compat/jansson) in this diff?

If you want to use it directly you can (if you do not add any new commits in the meantime):

```
git checkout master
git remote add mrbrdo https://github.com/mrbrdo/cgminer.git
git fetch mrbrdo
git reset --hard mrbrdo/kalroth
git push -f
```

What I did was clone the official cgminer on tag v3.7.2, made a diff with your "initial clone" version, commited that, then add yours as remote and cherry-pick all your commits after initial clone commit.

This will help people so they can check what you really changed.

Thanks!

**Comment by Kalroth** [comment]
All I did was to download the source from here: https://github.com/ckolivas/cgminer/tree/v3.7.2
I then added the download to git and implemented my changes.

I don't know about any jansson files, they're were in the 3.7.2 tree when i downloaded it.
The original readme is still there too, it's called README.cgminer3.7.2

I think the commit list is transparent enough: https://github.com/Kalroth/cgminer-3.7.2-kalroth/commits

**Comment by mrbrdo** [comment]
Then those files were probably created/removed when you compiled (I guess you made the commit after you already compiled). You are right about jansson, I misinterpreted, in the diff there are a few files added but it seems they are just from when you compiled.

It would be nice if you consider it, it is nice to have the commit history from original cgminer 3.7.2 tree. I will be glad to guide you through it to do it yourself if you don't trust my fork.

**Comment by mrbrdo** [comment]
If you want, this will take official cgminer 3.7.2 and apply all your commits on top (up to commit "Added BIOS information to --ndevs|-n listing."):

```
git clone git@github.com:ckolivas/cgminer.git
cd cgminer
git reset --hard v3.7.2

git remote add kalroth git@github.com:Kalroth/cgminer-3.7.2-kalroth.git
git fetch kalroth
git cherry-pick 4651e36e34207d54aef6f5e282a8f68d2badb8fd
git cherry-pick 7367ffe324eb3e7d9f94bff551b23b63abe14cf5
git cherry-pick 5e400fd3b78040a4c65c4a9384546714eb4e8006
git cherry-pick a3e93cd9b554f8211bfd5074304533f0873c129b
git cherry-pick cc024c2f230fa3de5fcc6bc12ee01250ee900bd4
git cherry-pick 9a19b3de41036b5e4acb5bcf8d5dc0f98633e11c
git cherry-pick b4a0f5c23ba96422ec1fa1aa9169c10d90a9338b
git cherry-pick eaa27bfe756740a2e4df81b59888e9a715f9c266
git cherry-pick f5c3034832eae01cdb78681f2570fac6e0462112
git cherry-pick 4989cf351b0614f9933733a270b2f7f0072befad
git cherry-pick 1ebdb4beead0a52bc62c2fabb25ab0ab78eb0464
git cherry-pick 40ff483116658bae1d304d60375eb9f8029df512
git cherry-pick 86a53fd70c62fb9ffeb1207770be5fb71fdfd83c
git cherry-pick e14d248b44b6350e806777f8164a68f6199e62df

# add back your readme and then git commit

git push -f kalroth master
```

Then you can do where you currently have your repo:

```
git checkout master
git fetch
git reset --hard origin/master
```

**Comment by veox** [comment]
Hey, thanks, @mrbrdo. I'll surely use this.

**Comment by Kalroth** [comment]
I think I did it correct, I am still a git novice. :)

The "git@github.com:" syntax didn't work for me, I had to convert it to http://.
Please take a look and see if I managed to f*ck anything up.

EDIT: Oh and in case it does work, thanks a lot for the help!

**Comment by mrbrdo** [comment]
Looks great! And welcome to github then ;)
