### ISSUE TITLE
Change/Add Version Information

### ISSUE THREAD

**Issue by cycl0ne** [Kalroth/cgminer-3.7.2-kalroth#11]
Hi,

we already talked in an email about this. Can you update the Versionnumber to 3.7.2.x ? Or make an CGminer+ 1.0.0 ? Its a bit problematic to check a mining rig if the newest cgminer-3.7.2-kalroth is running.

Thanks
C.

**Comment by Kalroth** [comment]
Bumped version number to 3.7.3 in this commit: https://github.com/Kalroth/cgminer-3.7.2-kalroth/commit/0df8ef4b0ad73deedd53cf104eaf808819c5e17d

It should now be easier to identify my branch. :)
