### ISSUE TITLE
GPU display/settings incorrect ordering

### ISSUE THREAD

**Issue by afloyd** [Kalroth/cgminer-3.7.2-kalroth#14]
I would like to start off by saying THANK YOU for this fork, me and my 290's LOVE IT! It was frustrating not being able to use the normal `q` command to exit the program. And then, adding the downclocking on exit made the system so much more stable! I had actually put in a request to cgwatcher for that very feature, guess I asked in the wrong place ;)

So I had 2 R9 290's installed, then added 2 R9 270's later... It was quite hard to track down this issue after adding the 270's, and I assume it exists in other cgminer repo's as well... So I'll try to describe best as possible, here's my settings (ones I'm using after I found out before they were incorrectly applied/swapped):

```
"gpu-engine" : "1025,1025,975,975",
"gpu-memclock" : "1500,1500,1400,1400",
"gpu-powertune" : "50,50,20,20",
"xintensity": "250,250,500,500", //(xintensity applied correctly)
```

I'm not sure if thread-concurrency applied correctly or not, although I'm assuming it did because the 290's still seem to be hashing as they were before adding the 270's. When I tried switching the order of the thread-concurrency, I got hardware errors so I do think they are working in the correct order as intended. My cards as they show up in the ncurses display are (determined by hashrate): 

```
GPU0: 270
GPU1: 270
GPU2: 290
GPU3: 290
```

i intended the 290's to have:

```
"gpu-engine" : "1025",
"gpu-memclock" : "1500",
"gpu-powertune" : "50"
```

But had to flip-flop some of the settings as shown above instead of as I would assume the parameters are read in according to GPU index. It's like they array of parameters is being read in descending index order, while being applied to the GPU's array read in ascending index order. I found this out by looking at each GPU in Trixx and the settings there didn't follow (based on GPU type) to what I had set them to in my config...

I'm not 100% sure, but I'm pretty confident that temp/RPM values shown in the ncurses display don't line up with the correct GPU either.

**Comment by Kalroth** [comment]
If you run cgminer -n then you get a full device list as cgminer sees them, because that is how AMD ADL sees them. That is the order you can use in your configuration file.

You can also use --gpu-map to reorder the devices in the order you wish to force a GPU order :

```
--gpu-map <arg>     Map OpenCL to ADL device order manually, paired CSV (e.g. 1:0,2:1 maps OpenCL 1 to ADL 0, 2 to 1)
```

**Comment by afloyd** [comment]
Awesome, that worked perfectly thanks!
