### ISSUE TITLE
No .bin created / read on startup

### ISSUE THREAD

**Issue by Nerdoholic** [Kalroth/cgminer-3.7.2-kalroth#16]
Hi,

when I am starting with intensity and thread-concurrency a .bin gets generated in case there is none. It is also read on future startups, skipping the internal calculation.

Though, when I set rawintensity, a .bin is neither generated nor read on startup.

Maybe you could add a recognition for x/raw intensity ? E.g.
scrypt130511Tahitiglg2xi8191w256l8.bin
scrypt130511Tahitiglg2ri8191w256l8.bin

I get another 10 KH/s with the modified .bin, and I'd rather not make a crude hack via "normal" startup and then altering the ri via the api :smile: 

Greetings
Oliver

PS: Since I really like your improvements I sent some coins to keep you motivated ;)

**Comment by Kalroth** [comment]
I cannot reproduce the issue you're experiencing, the scrypt kernel binary is created regardless of intensity, xintensity or rawintensity being used.

Additionally intensity has nothing to do with the binary image that is created, so it would make little sense to put it in the file name.

**Comment by Nerdoholic** [comment]
No wonder you can't reproduce it.
You probably don't start with "xintensity" : "8191", :sweat_smile:

Where is my button to delete stupid questions ? :smiley:
