### ISSUE TITLE
All cards return to stock settings 

### ISSUE THREAD

**Issue by phadcoin** [Kalroth/cgminer-3.7.2-kalroth#17]
Hello,

  I have been using your version of cgminer and I love it.  Thank you very much for the work.  I recently installed SMOS on my system and then installed your version of cgminer.  

  Something strange has been happening that I cannot seem to figure out.  It seems that after some time left alone (usually over night when I go to bed) that all the cards (3 x r9 290) have there setting put back to stock settings (947/1250).  It does not appear from the numbers of shares submitted that cgminer has restarted.  The thing that is even more strange is that my .conf file does not have the stock settings in it.

  Here is my conf file if needed:

"api-listen" : true,
"xintensity" : "256",
"vectors" : "1",
"worksize" : "256",
"kernel" : "scrypt",
"auto-fan" : true,
"temp-cutoff" : "99",
"temp-overheat" : "95",
"temp-target" : "88",
"expiry" : "30",
"gpu-dyninterval" : "7",
"log" : "5",
"queue" : "1",
"retry-pause" : "5",
"scan-time" : "30",
"scrypt" : true,
"temp-hysteresis" : "3",
"shares" : "0",
"thread-concurrency" : "20481,32765,20481",
"gpu-thread" : "1",
"gpu-engine" : "1000,1000,1000",
"sharethreads" : "32",
"lookup-gap" : "2",
"gpu-powertune" : "20",
"gpu-memclock" : "1500,1500,1500"

Any help would be great.

**Comment by Kalroth** [comment]
cgminer doesn't know what the stock settings and from the looks of it, you aren't telling it what they are either. I suppose it could be some BIOS or driver fail safe or something, but that would be the first time I've heard of it.

My guess is that an external program is to blame for it.

**Comment by phadcoin** [comment]
Thank you for the quick reply.  I will see what the SMOS guy says.  Maybe the API is doing that. 

 Cheers!
