### ISSUE TITLE
crash on "set idle" on 290

### ISSUE THREAD

**Issue by carly200** [Kalroth/cgminer-3.7.2-kalroth#19]
Hi,

I just upgraded from a Jan 30th build in Windows to the most recent one, and on my quad 290 rigs (on both) the computer freezes right after startup

I think it hast to do with:
--- 2014-02-01 -------------------------------------------------------------------------------
CHANGE:  Idle state for GPUs when there's no work.
gpu-engine and gpu-memclock exit values are applied when there's no work available. This should
prevent overclocked devices from going unstable when a pool goes down for a longer duration.

because that is the last thing I read in the logfile....
Any idea how to find the cause? older builds work, and sgminer 4.1 also does, so it must be a conflict with the newer update.

**Comment by Kalroth** [comment]
The idle state is only put in effect when there's no work, meaning when all your pools are dead and there's nothing to do. There's a clear log entry when it goes into effect, so it should be visible in cgminer.

applog(LOG_WARNING, "Setting GPUs to idle performance.");
applog(LOG_WARNING, "Setting GPUs back to maximum performance.");

it is likely something else if you don't see above messages, but I can't really say what it is without further information. Try running cgminer with 2>logfile.txt at the end to generate a log.

**Comment by carly200** [comment]
I am using betarigs, so my first pool is "dead" most of the time..
I saw the log entry setting GPUs to idle and nothing after it..

I restarted that system, tried other builds and reset the GPU settings. now sometimes it will work, sometimes it will crash, but only on the newest build...

I am already writing to the logfile... and "setting idle" was the last entry.
misterious..
