### ISSUE TITLE
Possible Memory Leak in 02-04 build

### ISSUE THREAD

**Issue by giveen** [Kalroth/cgminer-3.7.2-kalroth#23]
Randomly, I get a total crash of cgminer and wake up in the morning to find that my mining had stopped. Here is Windows event log

Faulting application name: cgminer.exe, version: 0.0.0.0, time stamp: 0x52f15400
Faulting module name: amdocl.dll, version: 10.0.1348.5, time stamp: 0x52a24325
Exception code: 0xc0000005
Fault offset: 0x001326d0
Faulting process id: 0x13f4
Faulting application start time: 0x01cf35b473cc9eae
Faulting application path: C:\Users\Jeremy\Desktop\karlorth\cgminer.exe
Faulting module path: C:\Windows\system32\amdocl.dll
Report Id: 88499980-a201-11e3-9253-94de8028a52a

Faulting application name: cgminer.exe, version: 0.0.0.0, time stamp: 0x52f15400
Faulting module name: amdocl.dll, version: 10.0.1348.5, time stamp: 0x52a24325
Exception code: 0xc0000005
Fault offset: 0x00196309
Faulting process id: 0x182c
Faulting application start time: 0x01cf34ce4e59a416
Faulting application path: C:\Users\Jeremy\Desktop\karlorth\cgminer.exe
Faulting module path: C:\Windows\system32\amdocl.dll
Report Id: e82690a9-a0cb-11e3-8d69-94de8028a52a

At first I assumed it was my amdocl.dll crashing as listed in the log, however, I did a full driver cleaner and reinstalled 13.12. I am running 2- R9270x and 1 - R9270.

**Comment by Kalroth** [comment]
It does look like a it's a crash in AMDs OpenCL driver, so if a driver reinstall didn't fix it, the problem is likely somewhere else, maybe with the hardware. Try without any overclocking and maybe disabling cards until you find the culprit.

There is sadly not much I can do with above crash report.

**Comment by giveen** [comment]
I appreciate the response. I'm pretty sure its just the crappy XFX. Toning down the settings seems to make it more stable.
