### ISSUE TITLE
temperature not showing after update

### ISSUE THREAD

**Issue by DDecoene** [Kalroth/cgminer-3.7.2-kalroth#28]
Hello,

Today i did a "git pull" and recompiled after the update. Now when I run cgminer the temperatures of my gpu's aren't showing. Did I forget to do something?

Regards.

**Comment by Kalroth** [comment]
Yup, you likely forgot to copy the ADL includes into the source folder, as per the readme. :)

**Comment by DDecoene** [comment]
No I did not forget. But, the strangest thing is, now i started cgminer again, it DOES show the temps... I did not change anything however. just restarted the process.
