### ISSUE TITLE
Temperature and fan speed doesn't match GPU number

### ISSUE THREAD

**Issue by ern1001** [Kalroth/cgminer-3.7.2-kalroth#29]
Thanks so much for your version of cgminer. I have a quad R290 rig using your 3.7.3 3/24/2014 build on windows 8.1  . These are shown as GPU 0,1,2,3 in cgminer.

I have identified which physical GPU matches the GPU number shown in cgminer by slowing down a fan and matching that to the GPU shown in cgminer.

I have also verified that if I slow down a fan, using the cgminer fan speed control, that the temperature raises on the physical GPU both in the cgminer temperature and with using an infrared thermometer on that GPU.

Here is the problem - I usually run all 4 GPU's at an intensity of 20. If I lower the intensity of GPU0 to 10, cgminer shows the expected hashrate drop from 895K to 65K. HOWEVER, the temperature on GPU0 as shown in cgminer and the IR  thermometer does not drop. Instead, the temperature of GPU3 drops both in cgminer and confirmed when I check GPU3 with the IR thermometer.

If I do the same for GPU1, then the hashrate drops for GPU1, but the temperature drops for GPU0.

If I do the same for GPU2, then both the hashrate and the temperature drops as expected for GPU2.

If I do the same for  GPU3, then the hashrate drops for GPU3, but the temperature drops for GPU1 .

So there seems to be some odd reporting problem in cgminer between how the reported hashrate is matched to a GPU number vs how the temperature is reported in a quad GPU system.

As an FYI - I am using a MSI Z77A-G45 motherboard. Here is how the GPU numbering appears vs the numbering in cgminer:

PCI0 - GPU0 according to cgminer
PCI1 - GPU2 according to cgminer
PCI2 - empty
PCI3 - empty
PCI4 - empty
PCI5 - GPU3 according to cgminer
PCI6 - GPU1 according to cgminer

I have attached a screen shot of the case where I lower the intensity on GPU0 and the temperature drops on GPU3. This is very repeatable and the above results repeat exactly the same each time I try it.
![gpu0](https://cloud.githubusercontent.com/assets/7097182/2556610/33f74830-b6d9-11e3-8bc6-e6fddf9ff360.PNG)

**Comment by Kalroth** [comment]
That looks like a OpenCL and ADL device order mismatch.

Check the gpu-map section in the GPU-README.

**Comment by ern1001** [comment]
Hi Martin - many thanks for the quick advice. Per your suggestion, I added the following to my bat file and now the temperatures/speeds/hashrates all match for each GPU.
--gpu-map 0:3,1:0,3:1
