### ISSUE TITLE
RPC json MH/s precision

### ISSUE THREAD

**Issue by mrbrdo** [Kalroth/cgminer-3.7.2-kalroth#5]
Hey,

I've been struggling a bit to figure this out, so I guess it wouldn't hurt to put it here.

The RPC json API seems to return the hashrate in MH/s with 2 decimal places. But looking at the code I only see indications that it should be 4 decimal places, so I am a little buffled. Obviously for GPU miners it would be a bit better to have 4 decimal places, so you can see e.g. 0.7515 MH/s which is 751.5 KH/s, which is same precision that you get in the command line interface.

I looked at api.c and it really seems like it should be 4 places:

``` c
            case API_MHS:
                sprintf(buf, "%.4f", *((double *)(root->data)));
```

What is even weirder is that the Total MH value has the same format string (`%.4f`), and in the response I get, it actually has 4 decimal places, unlike MHS av or MHS 5s. In the code the MHS av seems to be calculated from "Total MH" / "Device Elapsed", both values are returned from RPC and if I divide them manually I do get more decimal places. So really weird.

**Comment by Kalroth** [comment]
I just merged a fix that changes it from 2 digits to 4 digits yesterday, you're not referring to that?

https://github.com/Kalroth/cgminer-3.7.2-kalroth/commit/77179024c0761280a9b1aa06bc67777ffa0dc24d

**Comment by mrbrdo** [comment]
Oh! What a coincidence then. I am running a version I compiled about a week ago, but I was looking at the source from today, I assumed you had not changed it :)

Great work man! :+1:
