### ISSUE TITLE
Invalid config option --kernel 

### ISSUE THREAD

**Issue by Stassy** [Kalroth/cgminer-3.7.2-kalroth#6]
After using one of these API options switchpool:addpool:removepool:save (unable to determine which one, I'm just a user), one line is added in cgminer.conf that prevents cgminer to restart reading the full conf file: 
"kernel" : "scrypt,scrypt,scrypt,scrypt,scrypt"

When cgminer restarts, this error is shown: 
Error in configuration file, partially loaded.

Using "cgminer -T" indicates: 
Invalid config option --kernel: Cannot specify a kernel with scrypt

And when the faulty line is removed, everything is working. 
But a new command with API, add again this line.

EDIT: Tested on Windows

**Comment by Kalroth** [comment]
Thanks for the issue report. I've gone through the save config code and I believe I've squashed your issue - and a few others as well :)

I've updated my Windows binary and you can see above commit reference for code details.

**Comment by Stassy** [comment]
Thanks, working now.
