### ISSUE TITLE
GPU voltage for R9 290 series with switch --gpu-vddc doesnt work

### ISSUE THREAD

**Issue by starnetdev0** [Kalroth/cgminer-3.7.2-kalroth#9]
Hi Kalroth, first of all I would like to thank you for your great effort with all these fixes and improvements, they work really nice.

As you may probably know the command line switch for cgminer for adjusting the voltage doesnt work with the R9 290 series. At least it doesnt work in my Gigabyte cards ( GV-R929D5-4GD-B ) . I think it has something to be with the way the fans and voltage are handled in those new cards, which is totally different than in the old versions.

When you have time it will be really nice if we can get the --gpu-vddc switch working again. Currently I have to manually adjust (undervolt) it every time I reset the computer with MSI Afterburner 3.0.0 beta 18 and its very slow and annoying.

 Thank you very much :)

**Comment by Kalroth** [comment]
Sadly there is currently no way to set voltage for 290 through AMD drivers.
It's like that for a few other R9 cards as well.

Only way is to use an external application like MSI AfterBurner or Sapphire
TriXX, both use direct I2C communication to do it. And neither program is
open source, so there's no telling how they do it.

**Comment by starnetdev0** [comment]
Thank you so much for your answer. I will check it in the MSI Afterburner forum and ask for more information, maybe they would like to share some code or a simple external library to do it. 

I will also check if there is a command line enabled for any of those tools: MSI Afterburner, TriXX, or ASUS which could help in the process of autoundervolt / autounderclock the cards.

Another way would be to edit the BIOS and manually set the voltage and clocks to a fixed value which is known to work from previous tests, but this could be worse and dangerous for less experienced people.

**Comment by pmalek** [comment]
There is (supposedly) an option to set the voltage with use of ADL Overdrive6. I have tried to this but have not succeeded so far. There is a post on AMD developer forum 

http://devgurus.amd.com/message/1303185

**Comment by Kalroth** [comment]
Sadly it doesn't work with OverDrive6 either, I did try to implement it. AMD have simply not implemented VDDC control for the 290s yet (as well as other R9 cards as well).
